In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../../data/Test_Truncated.xlsx")
df

,Match ID 18Char,Completion Date,Match Support Contact Notes,Little ID,Big ID,Big County,Big Age,Big Occupation,Big: Military,Big Approved Date,...,Little Other Interests,Little Contact: Interest Finder - Career,Little Contact: Interest Finder - Personality,Little Contact: Interest Finder - Three Wishes,Little Gender,Little Participant: Race/Ethnicity,Little Birthdate,Little Mailing Address Census Block Group,Big Home Census Block Group,Big Employer/School Census Block Group
0,a1v2J0000027CXKQA2,2017-12-20,Question: Activities: Answer: BB and...,0032J00003PfqfqQAB,0032J00003Pgbpe,Ramsey,25,Student: High School,NaN,2017-12-04,...,NaN,NaN,NaN,NaN,Male,Asian,2006-11-01,NaN,NaN,NaN
1,a1v2J0000027CXKQA2,2018-01-19,Question: Activities: Answer: BB and...,0032J00003PfqfqQAB,0032J00003Pgbpe,Ramsey,25,Student: High School,NaN,2017-12-04,...,NaN,NaN,NaN,NaN,Male,Asian,2006-11-01,NaN,NaN,NaN
2,a1v2J0000027CXKQA2,2018-02-18,NaN,0032J00003PfqfqQAB,0032J00003Pgbpe,Ramsey,25,Student: High School,NaN,2017-12-04,...,NaN,NaN,NaN,NaN,Male,Asian,2006-11-01,NaN,NaN,NaN
3,a1v2J0000027JFCQA2,2018-12-05,Question: Activities: Answer: MEC me...,0032J00003PfqfDQAR,0032J00003PhOyf,Dakota,38,Tech: Engineer,NaN,2018-11-07,...,NaN,NaN,NaN,NaN,Male,Black or African American,2006-09-01,2.705302e+11,2.703706e+11,NaN
4,a1v2J0000027JFCQA2,2019-02-14,Question: Activities: Answer: MEC sp...,0032J00003PfqfDQAR,0032J00003PhOyf,Dakota,38,Tech: Engineer,NaN,2018-11-07,...,NaN,NaN,NaN,NaN,Male,Black or African American,2006-09-01,2.705302e+11,2.703706e+11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2561,a1vUX000000U9QrYAK,2024-08-05,BBBS August '24 Bigs Check-In Form w/ Nicki T...,003UX0000039ZUmYAM,003UX0000046mNp,Hennepin,47,"Medical: Doctor, Provider",No,2024-03-27,...,NaN,NaN,NaN,NaN,Female,Black or African American,2011-09-01,2.705302e+11,2.705303e+11,NaN
2562,a1vUX000000U9QrYAK,2024-09-09,BBBS September '24 Bigs Check-In Form w/ Nicki...,003UX0000039ZUmYAM,003UX0000046mNp,Hennepin,47,"Medical: Doctor, Provider",No,2024-03-27,...,NaN,NaN,NaN,NaN,Female,Black or African American,2011-09-01,2.705302e+11,2.705303e+11,NaN
2563,a1vUX000000al0PYAQ,2024-05-13,B_first_name said he had a really good time at...,003UX000002Ln7rYAC,003UX000003ge7X,Hennepin,33,Business: Marketing,No,2024-04-28,...,NaN,NaN,NaN,NaN,Male,American Indian or Alaska Native,2012-06-01,NaN,NaN,NaN
2564,a1vUX000000al0PYAQ,2024-07-16,I had a nice check in with B_first_name today....,003UX000002Ln7rYAC,003UX000003ge7X,Hennepin,33,Business: Marketing,No,2024-04-28,...,NaN,NaN,NaN,NaN,Male,American Indian or Alaska Native,2012-06-01,NaN,NaN,NaN
2565,a1vUX000000al0PYAQ,2024-10-04,PC and mentor completed match support contact ...,003UX000002Ln7rYAC,003UX000003ge7X,Hennepin,33,Business: Marketing,No,2024-04-28,...,NaN,NaN,NaN,NaN,Male,American Indian or Alaska Native,2012-06-01,NaN,NaN,NaN